"""Usage: python3 get_tweets.py <country> <max_tweets>"""
import csv
import tweepy
import sys
import pandas as pd

# Put Twitter API key and tokens here
api_key = ''
api_secret = ''
access_token = ''
access_token_secret = ''

# Country is passed as first argument value
country = sys.argv[1]

# Load the users CSV file generated by get_users.py
users_df = pd.read_csv('{country}_users.csv'.format(country=country), 
                       dialect='excel')
users = users_df['screen_name']

# Create the output CSV file
output_file_name = country + '_tweets.csv'
file = open(output_file_name, 'w')
output_csv = csv.writer(file)
header = (
    'user_id',
    'user_screen_name',
    'user_friends_count',
    'user_followers_count',
    'user_tweets_count',
    'user_created_at',
    'tweet_id',
    'tweet_timestamp',
    'tweet_source',
    'tweet_retweet_count',
    'tweet_favorited_count',
    'tweet_text',
    'tweet_longitude',
    'tweet_latitude'
)
output_csv.writerow(header)

# Create the tweepy authorization and api objects to query Twitter API
auth = tweepy.OAuthHandler(api_key, api_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit_notify=True, wait_on_rate_limit=True)

# Max tweets is passed as second argument value
max_number_of_tweets = int(sys.argv[2])

# For each user, request up to max_number_of_tweets
count = 0
for screen_name in users:
    for tweet in tweepy.Cursor(
            api.user_timeline, screen_name=screen_name).items(
            max_number_of_tweets):
        print(tweet.text)
        if tweet.geo is not None:
            longitude = tweet.coordinates['coordinates'][0]
            latitude = tweet.coordinates['coordinates'][1]
        else:
            longitude = latitude = None
        line = (
            tweet.author.id,
            tweet.author.screen_name,
            tweet.author.friends_count,
            tweet.author.followers_count,
            None,
            tweet.author.created_at,
            tweet.id,
            tweet.created_at,
            tweet.source,
            tweet.retweet_count,
            tweet.favorite_count,
            tweet.text.encode('utf8'),  # the tweet's text
            longitude,
            latitude
        )
        output_csv.writerow(line)
    file.flush()
print('\n\n Done: Obtained all Tweets')
